language: python
services:
  - docker

before_install:
  - pip install molecule
  - pip install molecule[docker]

jobs:
  include:
    - stage: role test
      name: govcsim provisioner role test
      python: 3.6
      script: molecule test
